### ISSUE TITLE
No handlers could be found for logger "onlykey.client"

### ISSUE THREAD

**Issue by SteffeyDev** [trustcrypto/python-onlykey#3]
On MacOS 10.12 I am getting the following error:

`No handlers could be found for logger "onlykey.client"
Traceback (most recent call last):
  File "/usr/local/bin/onlykey-cli", line 11, in <module>
    load_entry_point('onlykey==0.0.1', 'console_scripts', 'onlykey-cli')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.macosx-10.12-intel/egg/onlykey/cli.py", line 20, in <module>
  File "build/bdist.macosx-10.12-intel/egg/onlykey/client.py", line 98, in __init__
onlykey.client.OnlyKeyUnavailableException`

Not quite sure what to do with this, ideas? Thanks.

**Comment by SteffeyDev** [comment]
I didn't know you had to have it plugged int for this to work.

**Comment by tsileo** [comment]
Thanks for the report, I will make it clearer in the documentation!
