### ISSUE TITLE
[Python3] Error in get_public_key

### ISSUE THREAD

**Issue by haplo** [trustcrypto/python-onlykey#34]
```
Traceback (most recent call last):
  File "/usr/local/bin/onlykey-agent", line 10, in <module>
    sys.exit(run_agent())
  File "/home/fidel/Code/onlykey-agent/onlykey_agent/__main__.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/home/fidel/Code/onlykey-agent/onlykey_agent/__main__.py", line 140, in run_agent
    public_key = conn.get_public_key(label=label)
  File "/home/fidel/Code/onlykey-agent/onlykey_agent/client.py", line 58, in get_public_key
    h.update(label)
TypeError: Unicode-objects must be encoded before hashing
```

I will work on a fix.

**Comment by haplo** [comment]
My bad, the error is in `onlykey-agent`.
