### ISSUE TITLE
FIDO2 handling of "onlykey-cli" not working on windows10 20H2

### ISSUE THREAD

**Issue by donestefan** [trustcrypto/python-onlykey#42]
Hi,

I'm using the standalone exe in version v1.2.3
non-fido2 actions run without problem (like 'getlabels' and `fwversion` ).
All FIDO2 actions throw errors after entering the pin:

```
d:\test>onlykey-cli.exe credential ls
PIN:
Traceback (most recent call last):
  File "C:\Users\IEUser\Desktop\python-onlykey\tests\cli.py", line 6, in <module>
  File "onlykey\cli.py", line 745, in main
  File "onlykey\cli.py", line 295, in cli
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "solo\cli\key.py", line 542, in cred_ls
  File "solo\client.py", line 53, in find
solo.exceptions.NoSoloFoundError: no device found
[6040] Failed to execute script cli
```

The same happens on `ping` and `wink`.

I'm not sure where the path `C:\Users\IEUser\Desktop\python-onlykey\tests\cli.py` comes from. It certainly does not exist on my computer... Maybe some hardcoded fragment from your build environment?

**Comment by onlykey** [comment]
This is fixed here - https://github.com/trustcrypto/python-onlykey/releases/tag/v1.2.5
