### ISSUE TITLE
fido2 depency update

### ISSUE THREAD

**Issue by flumm** [trustcrypto/python-onlykey#43]
it seems that in the current versions published, the default install guide does not work (at least on debian 10)

if i install the dependencies, run `pip3 install onlykey` and run it, i get

```
Traceback (most recent call last):
  File "/home/flumm/.local/bin/onlykey-cli", line 6, in <module>
    from onlykey.cli import main
  File "/home/flumm/.local/lib/python3.7/site-packages/onlykey/cli.py", line 16, in <module>
    from solo.cli.key import key
  File "/home/flumm/.local/lib/python3.7/site-packages/solo/cli/__init__.py", line 17, in <module>
    from solo.cli.key import key
  File "/home/flumm/.local/lib/python3.7/site-packages/solo/cli/key.py", line 24, in <module>
    import solo.fido2
  File "/home/flumm/.local/lib/python3.7/site-packages/solo/fido2/__init__.py", line 3, in <module>
    import fido2._pyu2f
ModuleNotFoundError: No module named 'fido2._pyu2f'
```

it seems that the fido2 package had an update and others had also issues with that, see for example: https://github.com/Nitrokey/pynitrokey/issues/57

i solved it for now by installing the exact version with
`pip3 install fido2==0.8.1`
but it would be nice to have it working out of the box

**Comment by onlykey** [comment]
fix has been released to pypi version 1.2.4
