### ISSUE TITLE
Error when using onlykey-cli on Windows Subsystem for Linux (WSL)

### ISSUE THREAD

**Issue by tasso85** [trustcrypto/python-onlykey#52]
I was testing onlykey-cli on WSL, it installed correctly but fails when I try commands, for example:

```
mtassinari@TMA-21 ~
$ onlykey-cli
OnlyKey CLI v1.2.6
Control-D to exit.


OnlyKey> getlabels

Traceback (most recent call last):
  File "/usr/local/bin/onlykey-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/onlykey/cli.py", line 960, in main
    cli()
  File "/usr/local/lib/python3.8/dist-packages/onlykey/cli.py", line 530, in cli
    for slot in only_key.getlabels():
  File "/usr/local/lib/python3.8/dist-packages/onlykey/client.py", line 371, in getlabels
    self.send_message(msg=Message.OKGETLABELS)
  File "/usr/local/lib/python3.8/dist-packages/onlykey/client.py", line 267, in send_message
    self._hid.write(raw_bytes)
AttributeError: 'OnlyKey' object has no attribute '_hid'
```

Is usage on WSL supported?

**Comment by onlykey** [comment]
WSL2 does not support passing USB devices so there is not a way for the key to communicate with the app.

**Comment by tasso85** [comment]
My mistake then, I thought it was supported, sorry for opening this issue.
