### ISSUE TITLE
CTAP error: 0x35 - PIN_NOT_SET

### ISSUE THREAD

**Issue by TheOnAndOnlyZenomat** [trustcrypto/python-onlykey#68]
If I try to list my residential keys using `onlykey-cli credential info` and then type my OnlyKey pin, I receive the error
```
» onlykey-cli credential info                                                      zeno@NathanArch | 13:54:36
PIN: 
Traceback (most recent call last):
  File "/home/zeno/.local/bin/onlykey-cli", line 8, in <module>
    sys.exit(main())
  File "/home/zeno/.local/lib/python3.10/site-packages/onlykey/cli.py", line 1196, in main
    cli()
  File "/home/zeno/.local/lib/python3.10/site-packages/onlykey/cli.py", line 520, in cli
    solo.cli.key()
  File "/home/zeno/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/zeno/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/zeno/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zeno/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zeno/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zeno/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/zeno/.local/lib/python3.10/site-packages/solo/cli/key.py", line 533, in cred_info
    cm = client.cred_mgmt(pin)
  File "/home/zeno/.local/lib/python3.10/site-packages/solo/devices/base.py", line 116, in cred_mgmt
    token = client.client_pin.get_pin_token(pin)
  File "/home/zeno/.local/lib/python3.10/site-packages/fido2/ctap2/pin.py", line 260, in get_pin_token
    resp = self.ctap.client_pin(
  File "/home/zeno/.local/lib/python3.10/site-packages/fido2/ctap2/base.py", line 728, in client_pin
    return self.send_cbor(
  File "/home/zeno/.local/lib/python3.10/site-packages/fido2/ctap2/base.py", line 675, in send_cbor
    raise CtapError(status)
fido2.ctap.CtapError: CTAP error: 0x35 - PIN_NOT_SET
```
This happens with all `credential`-commands on the command line.
If I try to use it in the REPL, nothing happens and it returns to the prompt.
Other commands, like getkeylabels, work.

**Comment by onlykey** [comment]
> CTAP error: 0x35 - PIN_NOT_SET

This means you have no PIN set, also without a PIN you have no stored FIDO2 credentials

**Comment by TheOnAndOnlyZenomat** [comment]
With pin we are talking about the pin I use to unlock my key, right? Because I have set a pin

**Comment by TheOnAndOnlyZenomat** [comment]
Ah ok, then I missunderstood what the `credential` command is for, thank you
