### ISSUE TITLE
setpin option

### ISSUE THREAD

**Issue by onlykey** [trustcrypto/python-onlykey#8]
See cli.py 190 - 213

Trying to add setpin, setsdpin, and setpdpin commands

currently getting an error 

OnlyKey> setpin

Enter a 7-10 digit PIN on the OnlyKey keypad
Traceback (most recent call last):
  File "/usr/local/bin/onlykey-cli", line 11, in <module>
    load_entry_point('onlykey==0.0.1', 'console_scripts', 'onlykey-cli')()
  File "build/bdist.macosx-10.11-x86_64/egg/onlykey/cli.py", line 201, in main
  File "build/bdist.macosx-10.11-x86_64/egg/onlykey/cli.py", line 193, in cli
AttributeError: 'OnlyKey' object has no attribute 'setpin'

**Comment by tsileo** [comment]
I added a new `onlykey-init` command that will start a small wizard to setup the 3 pins, I updated the README.

**Comment by onlykey** [comment]
@tsileo I tested this out it works like a charm great job!
